name: Run integration tests
on:
  repository_dispatch:
    types:
      - start-workflow-run-tests
  workflow_dispatch:
    inputs:
      sharepoint_versions:
        description: 'SharePoint versions to deploy'
        required: true
        default: '["SE"]'
      skip_create_environment:
        description: 'Set to true to skip deployment of template and jump to artifacts installation'
        required: true
        default: false

jobs:
  call-workflow-prepare-dtl-env:
    uses: Yvand/EntraCP/.github/workflows/reusable-prepare-dtl-env.yml@master
    with:
      project-name: ${{ vars.PROJECT_NAME }}
      sharepoint-versions: ${{ inputs.sharepoint_versions }}
      skip-create-environment: ${{ inputs.skip_create_environment == 'true' }}
      dtl-serviceName: ${{ vars.dtl_serviceName }}
      dtl-rgName: ${{ vars.dtl_rgName }}
      dtl-environmentName: ${{ vars.dtl_environmentName }}
      dtl-subscriptionId: ${{ vars.dtl_subscriptionId }}
      azdevops-organizationName: ${{ vars.DTL_AZDEVOPSACCOUNT }}
      dtl-env-adminUserName: ${{ vars.dtl_adminUserName }}
      dtl-env-addPublicIPAddress: ${{ vars.dtl_addPublicIPAddress }}
      dtl-env-rdpTrafficAllowed: ${{ vars.dtl_RDPTrafficAllowed }}
      dtl-env-addAzureBastion: ${{ vars.dtl_addAzureBastion == 'true' }}
      test-prepareSharePointVmScriptUris: ${{ vars.DTL_PrepareSharePointVmScriptUris }}
      test-claimsProviderPackageUri: ${{ vars.DTL_ClaimsProviderPackageUri }}
      unittestfiles_azure_storage_share_relative_path: ${{ vars.unittestfiles_azure_storage_share_relative_path }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ADO_PAT_REGISTERAGENT: ${{ secrets.ADO_PAT_REGISTERAGENT }}
      DTL_ACCOUNTSPASSWORD: ${{ secrets.DTL_ACCOUNTSPASSWORD }}
      UNITTESTFILES_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.UNITTESTFILES_AZURE_STORAGE_CONNECTION_STRING }}
      UNITTESTFILES_AZURE_STORAGE_SHARE_NAME: ${{ secrets.UNITTESTFILES_AZURE_STORAGE_SHARE_NAME }}
